import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
    f1:{
        flex:1
    },
    fDRow:{
        flexDirection:"row"
    },
    jCCenter:{
        justifyContent:"center"
    },
    jCEnd:{
        justifyContent:"flex-end"
    },
    jCStart:{
        justifyContent:'flex-start'
    },
    aICenter:{
        alignItems:"center"
    },
    aIEnd:{
        alignItems:"flex-end"
    },
    aIStart:{
        alignItems:'flex-start'
    },
    fWWarp:{
        flexWrap:"wrap"
    },
    bgDark:{
        backgroundColor:"black"
    },
    bgDark2:{
        backgroundColor:"#2E2E2E"
    },
    bgGris:{
        backgroundColor:"gray"
    },
    bgNaranja:{
        backgroundColor:"orange"
    },
    textLight:{
        color:"white"
    },
    textDark:{
        color:"black"
    },
    textGray:{
        color:"gray"
    },
    textFZ1:{
        fontSize:10
    },
    textFZ2:{
        fontSize:20
    },
    textFZ3:{
        fontSize:30
    },
    textFZ4:{
        fontSize:40
    },
    mB1:{
        marginBottom:10
    },
    mB2:{
        marginBottom:20
    },
    mB3:{
        marginBottom:30
    },
    mT1:{
        marginTop:10
    },
    mT2:{
        marginTop:20
    },
    mT3:{
        marginTop:30
    },
    mL1:{
        marginLeft:10
    },
    mL2:{
        marginLeft:20
    },
    mL3:{
        marginLeft:30
    },
    mL4:{
        marginLeft:40
    },
    mL5:{
        marginLeft:50
    },
    mR1:{
        marginRight:10
    },
    mR2:{
        marginRight:20
    },
    mR3:{
        marginRight:30
    },
    mR4:{
        marginRight:40
    },
    mR5:{
        marginRight:50
    }
});